import './globals.css'
import { Inter } from 'next/font/google'
import {Grid, Box} from "@mui/material";
import Sidebar from "@/src/components/layout/sidebar";

const inter = Inter({ subsets: ['latin'] })
import {ThemeProviderClient} from "@/src/components/layout/theme";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <ThemeProviderClient>
              {children}
          </ThemeProviderClient>
      </body>
    </html>
  )
}
